AllCops:
  TargetRubyVersion: 2.5
  TargetRailsVersion: 5.2
  Exclude:
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'db/**/*'
    - 'tmp/**/*'
    - 'bin/**/*'

ClassAndModuleChildren:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Rails:
  Enabled: true
