version: "2"

services:
  db:
    image: postgres:10.5
    ports:
      - "5432:5432"

  redis:
    image: redis:4.0.11
    ports:
      - "6379:6379"

  memcache:
    image: memcached:1.5.10

  s3:
    image: minio/minio:latest
