version: "2"

services:
  db:
    image: postgres:10.5
    ports:
      - "5432:5432"
    volumes:
      - ./data/etc:/etc/postgresql
      - ./data/log:/var/log/postgresql
      - ./data/data:/var/lib/postgresql/data

  redis:
    image: redis:4.0.11
    ports:
      - "6379:6379"

  memcache:
    image: memcached:1.5.10

  s3:
    image: minio/minio:latest
    volumes:
     - ./data/s3:/data
    ports:
     - "9000:9000"
    environment:
     MINIO_ACCESS_KEY: minio
     MINIO_SECRET_KEY: minio123
    command: server ./data/s3
